AWSTemplateFormatVersion: "2010-09-09"
Description: BTG Frontend en Angular con S3 + CloudFront (OAC seguro, sin bucket policy pública)

Resources:
  # -------------------------
  # S3 Bucket privado
  # -------------------------
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "btg-frontend-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private

  # -------------------------
  # Origin Access Control (OAC) para CloudFront
  # -------------------------
  FrontendOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: btg-frontend-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # -------------------------
  # CloudFront Distribution
  # -------------------------
  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !Sub "${FrontendBucket}.s3.${AWS::Region}.amazonaws.com"
            Id: S3Origin
            S3OriginConfig: {}
            OriginAccessControlId: !Ref FrontendOAC
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: allow-all
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendDistribution}"


Outputs:
  FrontendBucketName:
    Description: Nombre del bucket S3 del frontend
    Value: !Ref FrontendBucket

  CloudFrontURL:
    Description: URL pública del frontend
    Value: !Sub "https://${FrontendDistribution.DomainName}"
